server {
    listen 8080 default_server;
    server_name _;

    root /app;

    # fcgi_protocol buffers request bodies in 1024 bytes
    client_max_body_size 1k;

    location /static {
    }

    location / {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
    }
}
