server {
    listen 8080 default_server;
    server_name _;

    root /app;

    location /static {
    }

    location / {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
    }
}
